# Generated by Django 5.2.6 on 2025-09-30 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.direccion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='JefeCuadrilla',
            fields=[
                ('id_cuadrilla', models.AutoField(primary_key=True, serialize=False)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.departamento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Territorial',
            fields=[
                ('id_territorial', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
