# Generated by Django 5.2.6 on 2025-09-30 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id_multimedia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('documento', 'Documento')], max_length=20)),
                ('archivo', models.FileField(upload_to='multimedia/')),
                ('id_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.jefecuadrilla')),
                ('id_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.estadosolicitud')),
                ('id_territorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.territorial')),
            ],
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.solicitud'),
        ),
    ]
