# Generated by Django 5.2.6 on 2025-09-30 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEncuesta',
            fields=[
                ('id_tipo_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.departamento')),
                ('id_tipo_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.tipoencuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField()),
                ('id_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
            ],
        ),
    ]
